name: Publish Backend Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code (full history for tagging)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate timestamp tag (Central Time)
        run: echo "TIMESTAMP=$(TZ='America/Chicago' date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Create & push Git tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a "$TIMESTAMP" -m "Release $TIMESTAMP"
          git push origin "$TIMESTAMP"
        env:
          TIMESTAMP: ${{ env.TIMESTAMP }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.backend
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/nerdhub-backend:${{ env.TIMESTAMP }}
            ghcr.io/${{ github.repository_owner }}/nerdhub-backend:latest